services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: openmsp:latest
    container_name: openmsp_container
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/db_data

volumes:
  sqlite_data: